version: '3'
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: zxcv
      MYSQL_DATABASE: tg_bot
      MYSQL_USER: tg_bot
      MYSQL_PASSWORD: tg_bot
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./target/TelegramBotParser.jar:/home/TelegramBotParser.jar
      - ./build_profiles/prod/chromedriver:/chromedriver
